### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by tkphd** [arc-lessons/security#10]
I'm interested in adapting some of this material for HPC Carpentry. At present, since there is no license, this material is "all rights reserved." Is that the intent, or is there a more permissive license associated with this work?

**Comment by james-grant1** [comment]
Apologies about the delay getting this sorted but a license (CC BY 4.0) has now been added. Would be great to get some of the content incorporated/added into the carpentries and happy to discuss if you want to reach out.
